version: '3.8'

services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"  # InfluxDB external port 9000, internal port 8086
    environment:
      INFLUXDB_DB: TPC_DT1415_Monitor  # Set your desired database name
      INFLUXDB_HTTP_AUTH_ENABLED: "false"  # Disable authentication
    restart: always  # Restart on reboot
    volumes:
      - influxdb_data_TPC_DT1415:/var/lib/influxdb  # Named volume for InfluxDB data
    networks:
      - monitoringTPC
    
  grafana:
    image: grafana/grafana
    ports:
      - "3010:3000"  # Grafana external port 3010, internal port 3000
    environment:
      GF_SECURITY_ADMIN_USER: "admin"  # Set admin username
      GF_SECURITY_ADMIN_PASSWORD: "TPC"  # Set admin password
    restart: always  # Restart on reboot
    volumes:
      - grafana_data_TPC_DT1415:/var/lib/grafana  # Named volume for Grafana data
    networks:
      - monitoringTPC

networks:
  monitoring:

volumes:
  influxdb_data_TPC_DT1415:  # Define named volume for InfluxDB associated to the TPC hv module monitor
  grafana_data_TPC_DT1415:    # Define named volume for Grafana associated to the TPC live monitor
